spring.application.name=Proyecto-web

# =========================================================
# SERVIDOR
# =========================================================
server.port=8081

# =========================================================
# DATASOURCE ORACLE AUTONOMOUS DATABASE + WALLET
# =========================================================
spring.datasource.url=jdbc:oracle:thin:@lenguajesv2_medium?TNS_ADMIN=C:/oracle_wallet
spring.datasource.username=ADMIN
spring.datasource.password=Parras992013*
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

# =========================================================
# HIKARI
# =========================================================
spring.datasource.hikari.pool-name=HikariOraclePool
spring.datasource.hikari.maximum-pool-size=5
spring.datasource.hikari.minimum-idle=1
spring.datasource.hikari.idle-timeout=30000
spring.datasource.hikari.max-lifetime=1800000
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.validation-timeout=5000
spring.datasource.hikari.auto-commit=true
spring.datasource.hikari.data-source-properties.oracle.net.tns_admin=C:/oracle_wallet

# =========================================================
# JPA / HIBERNATE
# =========================================================
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.OracleDialect
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true

# =========================================================
# THYMELEAF
# =========================================================
spring.thymeleaf.cache=false

# =========================================================
# LOGGING
# =========================================================
logging.level.org.springframework.security=DEBUG
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.orm.jdbc.bind=TRACE
logging.level.com.zaxxer.hikari=DEBUG
logging.level.oracle.jdbc=DEBUG